import type {Member} from "@/interfaces";

export function createMemberList(): Map<number, Member> {
  const memberListInit = new Map<number, Member>();
  memberListInit.set(33456, {id: 33456, name: "山田太郎", email: "yamada@example.com", points: 35, note: "初回特典あり", });
  memberListInit.set(33457, {id: 33457, name: "鈴木一郎", email: "suzuki@example.com", points: 53, note: "", });
  memberListInit.set(33458, {id: 33458, name: "中田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33459, {id: 33459, name: "一田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33460, {id: 33460, name: "二田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33461, {id: 33461, name: "三田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33462, {id: 33462, name: "四田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33463, {id: 33463, name: "五田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33464, {id: 33464, name: "六田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33465, {id: 33465, name: "七田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33466, {id: 33466, name: "八田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33467, {id: 33467, name: "九田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33468, {id: 33468, name: "十田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33469, {id: 33469, name: "十一田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33470, {id: 33470, name: "十二田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33471, {id: 33471, name: "十三田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33472, {id: 33472, name: "十四田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33473, {id: 33473, name: "十五田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33474, {id: 33474, name: "十六田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33475, {id: 33475, name: "十七田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33476, {id: 33476, name: "十八田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33477, {id: 33477, name: "十九田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33478, {id: 33478, name: "二十田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33479, {id: 33479, name: "二十一田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33480, {id: 33480, name: "二十二田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33481, {id: 33481, name: "二十三田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33482, {id: 33482, name: "二十四田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33483, {id: 33483, name: "二十五田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33484, {id: 33484, name: "二十六田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33485, {id: 33485, name: "二十七田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33486, {id: 33486, name: "二十八田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33487, {id: 33487, name: "二十九田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33488, {id: 33488, name: "三十田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33489, {id: 33489, name: "三十一田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33490, {id: 33490, name: "三十二田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33491, {id: 33491, name: "三十三田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33492, {id: 33492, name: "三十四田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33493, {id: 33493, name: "三十五田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33494, {id: 33494, name: "三十六田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  memberListInit.set(33495, {id: 33495, name: "三十七田英寿", email: "nakata@example.com", points: 0, note: "VIP顧客", });
  return memberListInit;
}